load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@npm//:@bufbuild/protoc-gen-es/package_json.bzl", protoc_gen_es = "bin")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_python//python:py_binary.bzl", "py_binary")
load("//packages:go.bzl", "go_protocol")
load("//packages:packages.bzl", "api_packages")
load("//packages:rust.bzl", "rust_cargo", "rust_protocol")

rust_cargo(name = "cargo")

exports_files([
    "Cargo.toml",
    "Cargo.lock",
])

rust_protocol(
    name = "rust_protocol",
    schema_workspace = "//schema:workspace",
)

py_binary(
    name = "update_rust",
    srcs = ["//tools:update_rust.py"],
    args = ["$(rootpath :rust_protocol)"],
    data = [":rust_protocol"],
    legacy_create_init = 0,
    main = "//tools:update_rust.py",
)

go_protocol(
    name = "go_protocol",
    asyncapis = [
        "//schema:speech_to_text.asyncapi.yaml",
        "//schema:text_to_speech.asyncapi.yaml",
    ],
    fixtures = "//tests:fixtures.json",
    go_plugin = "@org_golang_google_protobuf//cmd/protoc-gen-go",
    grpc_plugin = "@org_golang_google_grpc_cmd_protoc_gen_go_grpc//:protoc-gen-go-grpc",
    licenses = [
        "LICENSE",
        "NOTICE",
        ":protobuf_license",
    ],
    schema_workspace = "//schema:workspace",
)

py_binary(
    name = "update_go",
    srcs = ["//tools:update_go.py"],
    args = ["$(rootpath :go_protocol)"],
    data = [":go_protocol"],
    legacy_create_init = 0,
    main = "//tools:update_go.py",
)

npm_link_all_packages(name = "node_modules")

protoc_gen_es.protoc_gen_es_binary(name = "protoc_gen_es")

copy_file(
    name = "protobuf_license",
    src = "@protobuf//:LICENSE",
    out = "PROTOBUF_LICENSE",
)

exports_files([
    ".github/workflows/sync.yaml",
    "LICENSE",
    "NOTICE",
    "VERSION",
    "buf.yaml",
    "copy.bara.sky",
])

js_library(
    name = "release_workflow",
    srcs = [".github/workflows/release-please.yaml"],
    visibility = ["//tests:__pkg__"],
)

js_library(
    name = "release_publication_workflow",
    srcs = [".github/workflows/release.yaml"],
    visibility = ["//tests:__pkg__"],
)

js_library(
    name = "release_selection_workflow",
    srcs = [".github/workflows/release-select.yaml"],
    visibility = ["//tests:__pkg__"],
)

api_packages(
    name = "packages",
    asyncapis = [
        "//schema:speech_to_text.asyncapi.yaml",
        "//schema:text_to_speech.asyncapi.yaml",
    ],
    license_files = [
        "LICENSE",
        "NOTICE",
        ":protobuf_license",
    ],
    plugin = ":protoc_gen_es",
    protos = [
        "//schema/rime:speech_to_text_proto",
        "//schema/rime:text_to_speech_proto",
    ],
    schema_workspace = "//schema:workspace",
    templates = [
        "//packages:README.md",
        "//packages:python.toml",
        "//packages:javascript.json",
    ],
    version = "VERSION",
    visibility = ["//visibility:public"],
)

alias(
    name = "format",
    actual = "//tools:format",
)

alias(
    name = "format_check",
    actual = "//tools:format.check",
)

js_library(
    name = "schema_source_workflow",
    srcs = [".github/workflows/schema-source.yaml"],
    visibility = ["//tests:__pkg__"],
)
