load("@aspect_rules_js//js:defs.bzl", "js_test")
load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "registry_verification_test",
    size = "small",
    srcs = ["registry_verification_test.py"],
    legacy_create_init = 0,
    deps = ["//tools:release"],
)

py_test(
    name = "compatibility_test",
    size = "small",
    srcs = ["compatibility_test.py"],
    args = [
        "$(rootpath @rules_buf_toolchains//:buf)",
        "$(rootpath //schema:workspace)",
    ],
    data = [
        "//schema:workspace",
        "@rules_buf_toolchains//:buf",
    ],
    legacy_create_init = 0,
    deps = ["//tools:compatibility"],
)

js_test(
    name = "release_publication_workflow_test",
    size = "small",
    args = [
        "$(rootpath //:release_publication_workflow)",
        "$(rootpath //:release_selection_workflow)",
    ],
    data = [
        "//:release_publication_workflow",
        "//:release_selection_workflow",
    ],
    entry_point = "release_publication_workflow_test.mjs",
)

js_test(
    name = "release_workflow_test",
    size = "small",
    args = ["$(rootpath //:release_workflow)"],
    data = ["//:release_workflow"],
    entry_point = "release_workflow_test.mjs",
)

py_test(
    name = "release_automation_test",
    size = "small",
    srcs = ["release_automation_test.py"],
    legacy_create_init = 0,
    deps = ["//tools:release"],
)

py_test(
    name = "release_test",
    size = "small",
    srcs = ["release_test.py"],
    args = ["$(rootpath //:packages)"],
    data = ["//:packages"],
    legacy_create_init = 0,
    deps = ["//tools:release"],
)

py_test(
    name = "sync_workflow_test",
    size = "small",
    srcs = ["sync_workflow_test.py"],
    args = ["$(rootpath //:.github/workflows/sync.yaml)"],
    data = ["//:.github/workflows/sync.yaml"],
    legacy_create_init = 0,
)

py_test(
    name = "packages_test",
    size = "small",
    srcs = ["packages_test.py"],
    args = [
        "--packages",
        "$(rootpath //:packages)",
        "--fixtures",
        "$(rootpath :fixtures.json)",
    ],
    data = [
        "fixtures.json",
        "//:packages",
    ],
    legacy_create_init = 0,
    deps = [
        "@pip//googleapis_common_protos",
        "@pip//protobuf",
    ],
)

js_test(
    name = "javascript_test",
    size = "small",
    args = [
        "$(rootpath //:packages)",
        "$(rootpath :fixtures.json)",
    ],
    data = [
        "fixtures.json",
        "//:node_modules/@bufbuild/protobuf",
        "//:node_modules/typescript",
        "//:packages",
    ],
    entry_point = "javascript_test.mjs",
)

py_test(
    name = "copybara_test",
    size = "medium",
    srcs = ["copybara_test.py"],
    args = [
        "--copybara",
        "$(rootpath //tools:copybara)",
        "--configuration",
        "$(rootpath //:copy.bara.sky)",
    ],
    data = [
        "//:copy.bara.sky",
        "//tools:copybara",
    ],
    legacy_create_init = 0,
)

py_test(
    name = "schema_source_test",
    size = "small",
    srcs = ["schema_source_test.py"],
    args = ["$(rootpath //:copy.bara.sky)"],
    data = ["//:copy.bara.sky"],
    legacy_create_init = 0,
    deps = ["//tools:schema_source"],
)

js_test(
    name = "schema_source_workflow_test",
    size = "small",
    args = ["$(rootpath //:schema_source_workflow)"],
    data = ["//:schema_source_workflow"],
    entry_point = "schema_source_workflow_test.mjs",
)

exports_files(["fixtures.json"])

py_test(
    name = "update_go_test",
    size = "small",
    srcs = ["update_go_test.py"],
    legacy_create_init = 0,
    deps = ["//tools:go_updater"],
)
