// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.0
// source: rime/speech_to_text.proto

package rimeapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeechToText_Transcribe_FullMethodName          = "/rime.SpeechToText/Transcribe"
	SpeechToText_TranscribeStreaming_FullMethodName = "/rime.SpeechToText/TranscribeStreaming"
)

// SpeechToTextClient is the client API for SpeechToText service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Whole-utterance and realtime speech recognition for Cassowary. Cassowary
// adapts this public contract to the native vLLM chat API; vLLM owns model
// loading, inference, and GPU scheduling.
type SpeechToTextClient interface {
	// Transcribes one complete WAV payload. Language and formatting mode are
	// available for the whole-utterance model path.
	Transcribe(ctx context.Context, in *TranscriptionRequest, opts ...grpc.CallOption) (*TranscriptionResponse, error)
	// Transcribes exactly one realtime PCM16 mono 16 kHz utterance per client
	// stream. The first request must contain `config`; following requests contain
	// audio. Client half-close commits the utterance and produces one final `done`
	// response. Dropping either side of the RPC cancels the associated backend
	// work.
	TranscribeStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingTranscriptionRequest, StreamingTranscriptionResponse], error)
}

type speechToTextClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechToTextClient(cc grpc.ClientConnInterface) SpeechToTextClient {
	return &speechToTextClient{cc}
}

func (c *speechToTextClient) Transcribe(ctx context.Context, in *TranscriptionRequest, opts ...grpc.CallOption) (*TranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscriptionResponse)
	err := c.cc.Invoke(ctx, SpeechToText_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speechToTextClient) TranscribeStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingTranscriptionRequest, StreamingTranscriptionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpeechToText_ServiceDesc.Streams[0], SpeechToText_TranscribeStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamingTranscriptionRequest, StreamingTranscriptionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeechToText_TranscribeStreamingClient = grpc.BidiStreamingClient[StreamingTranscriptionRequest, StreamingTranscriptionResponse]

// SpeechToTextServer is the server API for SpeechToText service.
// All implementations must embed UnimplementedSpeechToTextServer
// for forward compatibility.
//
// Whole-utterance and realtime speech recognition for Cassowary. Cassowary
// adapts this public contract to the native vLLM chat API; vLLM owns model
// loading, inference, and GPU scheduling.
type SpeechToTextServer interface {
	// Transcribes one complete WAV payload. Language and formatting mode are
	// available for the whole-utterance model path.
	Transcribe(context.Context, *TranscriptionRequest) (*TranscriptionResponse, error)
	// Transcribes exactly one realtime PCM16 mono 16 kHz utterance per client
	// stream. The first request must contain `config`; following requests contain
	// audio. Client half-close commits the utterance and produces one final `done`
	// response. Dropping either side of the RPC cancels the associated backend
	// work.
	TranscribeStreaming(grpc.BidiStreamingServer[StreamingTranscriptionRequest, StreamingTranscriptionResponse]) error
	mustEmbedUnimplementedSpeechToTextServer()
}

// UnimplementedSpeechToTextServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeechToTextServer struct{}

func (UnimplementedSpeechToTextServer) Transcribe(context.Context, *TranscriptionRequest) (*TranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedSpeechToTextServer) TranscribeStreaming(grpc.BidiStreamingServer[StreamingTranscriptionRequest, StreamingTranscriptionResponse]) error {
	return status.Error(codes.Unimplemented, "method TranscribeStreaming not implemented")
}
func (UnimplementedSpeechToTextServer) mustEmbedUnimplementedSpeechToTextServer() {}
func (UnimplementedSpeechToTextServer) testEmbeddedByValue()                      {}

// UnsafeSpeechToTextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechToTextServer will
// result in compilation errors.
type UnsafeSpeechToTextServer interface {
	mustEmbedUnimplementedSpeechToTextServer()
}

func RegisterSpeechToTextServer(s grpc.ServiceRegistrar, srv SpeechToTextServer) {
	// If the following call panics, it indicates UnimplementedSpeechToTextServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeechToText_ServiceDesc, srv)
}

func _SpeechToText_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechToTextServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeechToText_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechToTextServer).Transcribe(ctx, req.(*TranscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeechToText_TranscribeStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpeechToTextServer).TranscribeStreaming(&grpc.GenericServerStream[StreamingTranscriptionRequest, StreamingTranscriptionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeechToText_TranscribeStreamingServer = grpc.BidiStreamingServer[StreamingTranscriptionRequest, StreamingTranscriptionResponse]

// SpeechToText_ServiceDesc is the grpc.ServiceDesc for SpeechToText service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechToText_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rime.SpeechToText",
	HandlerType: (*SpeechToTextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _SpeechToText_Transcribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranscribeStreaming",
			Handler:       _SpeechToText_TranscribeStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rime/speech_to_text.proto",
}
